server {
    listen 80;

    # Vue 前端
    location / {
        root /var/www/vue;
        index index.html;
        try_files $uri /index.html;
    }

    # Laravel API
    location /api/ {
        root /var/www/backend/public;
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass backend:8000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public$fastcgi_script_name;
    }
}